baseURL: https://aprd.ir
languageCode: 'fa'
defaultContentLanguage: 'fa'
title: 'روزنوشته‌های امیرپورمند'
theme: "PaperMod"
paginate: 10


enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

publishDir: "docs"

googleAnalytics: G-NKCR60T4BL
minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: روزنوشته‌های امیرپورمند
  description: "ExampleSite description"
  keywords: [Blog, ]
  author: "امیر"
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: سلام امیر پورمند هستم
    Content: >
        سلام اینجا قدری درباره همه چیز می‌نویسم

  socialIcons:
    - name: twitter
      url: "https://twitter.com/pourmand_amir"
    - name: stackoverflow
      url: "https://stackoverflow.com/"
    - name: github
      url: "https://github.com/pourmand1376"

  analytics:
    google:
      SiteVerificationTag: "0UgRGp760ZWT9RdluFfKbknSLmu2SOzDh5TJvTHwKjE"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: https://github.com/pourmand1376/hugo-papermod-farsi-template/tree/publish_site/content
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

permalinks:
# https://gohugo.io/content-management/urls/
    posts: "/:filename/"
    

menu:
  main:
    - identifier: FATags
      name: تگ‌ها
      url: /fatags/
      weight: 20
    - identifier: archives
      name: آرشیو
      url: /archives/
      weight: 30

languages:
    fa:
        languageName: "farsi"
        weight: 1
        languagedirection: rtl
        taxonomies:
          category: categories
          tag: fatags
          series: series